  name: 'Prepare Toolchain'

  runs:
    using: "composite"
    steps:
      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy rustfmt
          cache-workspaces: .
          cache-directories: ./target

      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /home/runner/.cargo/bin/buck2
          key: buck2-binary
